#!/usr/bin/python3
import sys


def fc():
    """
    function fc to search file to convert number and format n=p*q
    """
    try:
        myfile = sys.argv[1]
        with open(myfile) as f:
            for factnumber in f:
                factnumber = int(factnumber)
                if factnumber % 2 == 0:
                        print("{}={}*{}".format(factnumber, factnumber // 2, 2))
                        continue
                i = 3
                while i < factnumber // 2:
                    if factnumber % i == 0:
                        print("{}={}*{}".format(factnumber, factnumber // i, i))
                        break
                    i = i + 2
                if i == (factnumber // 2) + 1:
                    print("{}={}*{}".format(factnumber, factnumber, 1))
    except (IndexError):
        pass


fc()
